/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MeRouteImport } from './routes/me'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as CafeRouteImport } from './routes/cafe'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as MeFriendsRouteImport } from './routes/me.friends'
import { Route as InviteInviteIdRouteImport } from './routes/invite.$inviteId'
import { Route as ClassClassIdRouteImport } from './routes/class.$classId'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminWaiversRouteImport } from './routes/admin.waivers'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as AdminStaffRouteImport } from './routes/admin.staff'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchedulingRouteImport } from './routes/admin.scheduling'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPromotionsRouteImport } from './routes/admin.promotions'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminInstallAppRouteImport } from './routes/admin.install-app'
import { Route as AdminGuidesRouteImport } from './routes/admin.guides'
import { Route as AdminEmailRouteImport } from './routes/admin.email'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminClientCommsRouteImport } from './routes/admin.client-comms'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminCheckInRouteImport } from './routes/admin.check-in'
import { Route as AdminChallengeRouteImport } from './routes/admin.challenge'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminBadgesRouteImport } from './routes/admin.badges'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin.customers.$customerId'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CafeRoute = CafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const MeFriendsRoute = MeFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => MeRoute,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassClassIdRoute = ClassClassIdRouteImport.update({
  id: '/class/$classId',
  path: '/class/$classId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminWaiversRoute = AdminWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulingRoute = AdminSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromotionsRoute = AdminPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstallAppRoute = AdminInstallAppRouteImport.update({
  id: '/install-app',
  path: '/install-app',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientCommsRoute = AdminClientCommsRouteImport.update({
  id: '/client-comms',
  path: '/client-comms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChallengeRoute = AdminChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/challenge': typeof ChallengeRoute
  '/faq': typeof FaqRoute
  '/goals': typeof GoalsRoute
  '/me': typeof MeRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/pricing': typeof PricingRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/client-comms': typeof AdminClientCommsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/email': typeof AdminEmailRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/install-app': typeof AdminInstallAppRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/waivers': typeof AdminWaiversRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/me/friends': typeof MeFriendsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/challenge': typeof ChallengeRoute
  '/faq': typeof FaqRoute
  '/goals': typeof GoalsRoute
  '/me': typeof MeRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/pricing': typeof PricingRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/client-comms': typeof AdminClientCommsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/email': typeof AdminEmailRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/install-app': typeof AdminInstallAppRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/waivers': typeof AdminWaiversRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/me/friends': typeof MeFriendsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/bookings': typeof BookingsRoute
  '/cafe': typeof CafeRoute
  '/challenge': typeof ChallengeRoute
  '/faq': typeof FaqRoute
  '/goals': typeof GoalsRoute
  '/me': typeof MeRouteWithChildren
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/packages': typeof PackagesRoute
  '/pricing': typeof PricingRoute
  '/rewards': typeof RewardsRoute
  '/schedule': typeof ScheduleRoute
  '/admin/badges': typeof AdminBadgesRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/challenge': typeof AdminChallengeRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/client-comms': typeof AdminClientCommsRoute
  '/admin/customers': typeof AdminCustomersRouteWithChildren
  '/admin/email': typeof AdminEmailRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/install-app': typeof AdminInstallAppRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/promotions': typeof AdminPromotionsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/scheduling': typeof AdminSchedulingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/admin/waivers': typeof AdminWaiversRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/class/$classId': typeof ClassClassIdRoute
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/me/friends': typeof MeFriendsRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/cafe'
    | '/challenge'
    | '/faq'
    | '/goals'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/pricing'
    | '/rewards'
    | '/schedule'
    | '/admin/badges'
    | '/admin/bookings'
    | '/admin/challenge'
    | '/admin/check-in'
    | '/admin/classes'
    | '/admin/client-comms'
    | '/admin/customers'
    | '/admin/email'
    | '/admin/guides'
    | '/admin/install-app'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/waivers'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/class/$classId'
    | '/invite/$inviteId'
    | '/me/friends'
    | '/payment/success'
    | '/admin/'
    | '/admin/customers/$customerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bookings'
    | '/cafe'
    | '/challenge'
    | '/faq'
    | '/goals'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/pricing'
    | '/rewards'
    | '/schedule'
    | '/admin/badges'
    | '/admin/bookings'
    | '/admin/challenge'
    | '/admin/check-in'
    | '/admin/classes'
    | '/admin/client-comms'
    | '/admin/customers'
    | '/admin/email'
    | '/admin/guides'
    | '/admin/install-app'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/waivers'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/class/$classId'
    | '/invite/$inviteId'
    | '/me/friends'
    | '/payment/success'
    | '/admin'
    | '/admin/customers/$customerId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/bookings'
    | '/cafe'
    | '/challenge'
    | '/faq'
    | '/goals'
    | '/me'
    | '/messages'
    | '/notifications'
    | '/onboarding'
    | '/packages'
    | '/pricing'
    | '/rewards'
    | '/schedule'
    | '/admin/badges'
    | '/admin/bookings'
    | '/admin/challenge'
    | '/admin/check-in'
    | '/admin/classes'
    | '/admin/client-comms'
    | '/admin/customers'
    | '/admin/email'
    | '/admin/guides'
    | '/admin/install-app'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/promotions'
    | '/admin/reports'
    | '/admin/schedule'
    | '/admin/scheduling'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/transactions'
    | '/admin/waivers'
    | '/auth/callback'
    | '/auth/reset-password'
    | '/class/$classId'
    | '/invite/$inviteId'
    | '/me/friends'
    | '/payment/success'
    | '/admin/'
    | '/admin/customers/$customerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BookingsRoute: typeof BookingsRoute
  CafeRoute: typeof CafeRoute
  ChallengeRoute: typeof ChallengeRoute
  FaqRoute: typeof FaqRoute
  GoalsRoute: typeof GoalsRoute
  MeRoute: typeof MeRouteWithChildren
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  PackagesRoute: typeof PackagesRoute
  PricingRoute: typeof PricingRoute
  RewardsRoute: typeof RewardsRoute
  ScheduleRoute: typeof ScheduleRoute
  ClassClassIdRoute: typeof ClassClassIdRoute
  InviteInviteIdRoute: typeof InviteInviteIdRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cafe': {
      id: '/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof CafeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me/friends': {
      id: '/me/friends'
      path: '/friends'
      fullPath: '/me/friends'
      preLoaderRoute: typeof MeFriendsRouteImport
      parentRoute: typeof MeRoute
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$classId': {
      id: '/class/$classId'
      path: '/class/$classId'
      fullPath: '/class/$classId'
      preLoaderRoute: typeof ClassClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin/waivers': {
      id: '/admin/waivers'
      path: '/waivers'
      fullPath: '/admin/waivers'
      preLoaderRoute: typeof AdminWaiversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scheduling': {
      id: '/admin/scheduling'
      path: '/scheduling'
      fullPath: '/admin/scheduling'
      preLoaderRoute: typeof AdminSchedulingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promotions': {
      id: '/admin/promotions'
      path: '/promotions'
      fullPath: '/admin/promotions'
      preLoaderRoute: typeof AdminPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/install-app': {
      id: '/admin/install-app'
      path: '/install-app'
      fullPath: '/admin/install-app'
      preLoaderRoute: typeof AdminInstallAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/client-comms': {
      id: '/admin/client-comms'
      path: '/client-comms'
      fullPath: '/admin/client-comms'
      preLoaderRoute: typeof AdminClientCommsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/challenge': {
      id: '/admin/challenge'
      path: '/challenge'
      fullPath: '/admin/challenge'
      preLoaderRoute: typeof AdminChallengeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/badges': {
      id: '/admin/badges'
      path: '/badges'
      fullPath: '/admin/badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers/$customerId': {
      id: '/admin/customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AdminRouteChildren {
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminChallengeRoute: typeof AdminChallengeRoute
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminClientCommsRoute: typeof AdminClientCommsRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminEmailRoute: typeof AdminEmailRoute
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminInstallAppRoute: typeof AdminInstallAppRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminPromotionsRoute: typeof AdminPromotionsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSchedulingRoute: typeof AdminSchedulingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminWaiversRoute: typeof AdminWaiversRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBadgesRoute: AdminBadgesRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminChallengeRoute: AdminChallengeRoute,
  AdminCheckInRoute: AdminCheckInRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminClientCommsRoute: AdminClientCommsRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminEmailRoute: AdminEmailRoute,
  AdminGuidesRoute: AdminGuidesRoute,
  AdminInstallAppRoute: AdminInstallAppRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminPromotionsRoute: AdminPromotionsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSchedulingRoute: AdminSchedulingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminWaiversRoute: AdminWaiversRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface MeRouteChildren {
  MeFriendsRoute: typeof MeFriendsRoute
}

const MeRouteChildren: MeRouteChildren = {
  MeFriendsRoute: MeFriendsRoute,
}

const MeRouteWithChildren = MeRoute._addFileChildren(MeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BookingsRoute: BookingsRoute,
  CafeRoute: CafeRoute,
  ChallengeRoute: ChallengeRoute,
  FaqRoute: FaqRoute,
  GoalsRoute: GoalsRoute,
  MeRoute: MeRouteWithChildren,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  PackagesRoute: PackagesRoute,
  PricingRoute: PricingRoute,
  RewardsRoute: RewardsRoute,
  ScheduleRoute: ScheduleRoute,
  ClassClassIdRoute: ClassClassIdRoute,
  InviteInviteIdRoute: InviteInviteIdRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
